[tools]
bat = "0.26.1"
btop = "1.4.6"
chezmoi = "latest"
difftastic = "0.67.0"
doggo = "1.1.4"
eza = "latest"
fzf = "0.72.0"
"github:pythops/bluetui" = "latest"
"github:tldr-pages/tldr" = "latest"
neovim = "0.12.1"
ripgrep = "15.1.0"
starship = "1.24.2"
zoxide = "0.9.9"
